language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.6

install:
  - pip install -r requirements.txt

script: 
  - python setup.py build_ext --inplace
  - nosetests -s -v
